### ISSUE TITLE
能否推荐一个本普通人能看懂的哥德尔的证明？

### ISSUE THREAD

**Issue by qiulang** [alaskasquirrel/KurtGodel#1]
你好，我对哥德尔经历也好着迷，你列的书，我也看了几本。但还是没看到一本能够让我理解证明的书 ，比如 《哥德尔证明》那本我看完觉得还是不完全理解。你有什么推荐吗？

**Comment by alaskasquirrel** [comment]
抱歉，未能及时回复你的消息。

普通人想要直接领会不完备性定理，恐有难度。本人正自学数理逻辑，弥补缺失。

Raymond M. Smullyan(1919-2017) 著：
* < *A Beginner's Guide to Mathematical Logic* >中译《[数理逻辑入门](https://book.douban.com/subject/33428095/)》 
* < *A Beginner's Further Guide to Mathematical Logic* > 进阶
* 《[哥德尔不完备性定理](https://book.douban.com/subject/30457524/)》< *Godel's Incompleteness Theorems* >
* < *The Godelian Puzzle Book: Puzzles, Paradoxes and Proofs* >

国内B站 还有 **刘晓力** 老师的讲座可供了解。

**Comment by qiulang** [comment]
真巧 我刚买了 The Godelian Puzzle Book: Puzzles, Paradoxes and Proofs
这本你觉得普通人可以看明白？

**Comment by alaskasquirrel** [comment]
个人涉猎有限，感觉The Godelian Puzzle Book 像是综述，倘若没有相应的数理逻辑基础，恐难以参透精髓。
Smullyan 本人即是自动推理领域的专家，它的多本著作价值颇高。

< *Godel's Incompleteness Theorems* > 就是对哥德尔不完备定理的简化。这里的"简化"对我而言还是复杂的，里面涉及到Tarski的工作理念。

**Comment by qiulang** [comment]
是的，我也买了 《哥德尔不完备性定理》没看懂 :$  其实我最早是看 Ernest Nagel 写的哥德尔的证明，那是很多年前的事，当时没看懂，就一直留下遗憾和心病。总想找机会再挑战下自己。
